-- ============================================================
-- PostureGuard AI - Migration từ schema cũ (v3/v4) lên v5
-- Mục tiêu: GIỮ NGUYÊN dữ liệu hiện có, chỉ bổ sung/chuẩn hóa.
-- Có thể chạy nhiều lần (idempotent ở mức thực tế).
-- ============================================================

begin;

-- ------------------------------------------------------------
-- 0. Bảng ghi nhận migration
-- ------------------------------------------------------------
create table if not exists public.app_migrations (
  version text primary key,
  applied_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- 1. USER_PROFILES
-- Giữ lại các cột cũ như selected_model, parent_alert_seconds,
-- report_schedule nếu đang tồn tại. V5 không còn dùng chúng.
-- ------------------------------------------------------------
create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade
);

alter table public.user_profiles
  add column if not exists student_name text,
  add column if not exists parent_email text,
  add column if not exists local_alert_seconds integer,
  add column if not exists email_enabled boolean,
  add column if not exists updated_at timestamptz;

update public.user_profiles
set
  student_name = coalesce(student_name, ''),
  parent_email = coalesce(parent_email, ''),
  local_alert_seconds = coalesce(local_alert_seconds, 10),
  email_enabled = coalesce(email_enabled, true),
  updated_at = coalesce(updated_at, now());

alter table public.user_profiles
  alter column student_name set default '',
  alter column parent_email set default '',
  alter column local_alert_seconds set default 10,
  alter column email_enabled set default true,
  alter column updated_at set default now();

alter table public.user_profiles
  alter column student_name set not null,
  alter column parent_email set not null,
  alter column local_alert_seconds set not null,
  alter column email_enabled set not null,
  alter column updated_at set not null;

-- Check local_alert_seconds >= 3, chỉ thêm nếu chưa có.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'user_profiles_local_alert_seconds_check'
      and conrelid = 'public.user_profiles'::regclass
  ) then
    alter table public.user_profiles
      add constraint user_profiles_local_alert_seconds_check
      check (local_alert_seconds >= 3);
  end if;
end $$;

-- ------------------------------------------------------------
-- 2. SYSTEM_CONFIG
-- V5: model là cấu hình CHUNG toàn hệ thống.
-- ------------------------------------------------------------
create table if not exists public.system_config (
  id integer primary key
);

alter table public.system_config
  add column if not exists selected_model text,
  add column if not exists model_version text,
  add column if not exists model_url text,
  add column if not exists updated_at timestamptz;

update public.system_config
set
  selected_model = coalesce(selected_model, 'cnn'),
  model_version = coalesce(model_version, 'v1'),
  model_url = coalesce(model_url, ''),
  updated_at = coalesce(updated_at, now());

insert into public.system_config(id, selected_model, model_version, model_url, updated_at)
select 1, 'cnn', 'v1', '', now()
where not exists (select 1 from public.system_config where id = 1);

alter table public.system_config
  alter column selected_model set default 'cnn',
  alter column model_version set default 'v1',
  alter column model_url set default '',
  alter column updated_at set default now();

alter table public.system_config
  alter column selected_model set not null,
  alter column model_version set not null,
  alter column model_url set not null,
  alter column updated_at set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'system_config_id_check'
      and conrelid = 'public.system_config'::regclass
  ) then
    alter table public.system_config
      add constraint system_config_id_check check (id = 1);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'system_config_selected_model_check'
      and conrelid = 'public.system_config'::regclass
  ) then
    alter table public.system_config
      add constraint system_config_selected_model_check
      check (selected_model in ('cnn','resnet50','densenet121','efficientnetb0'));
  end if;
end $$;

-- ------------------------------------------------------------
-- 3. MODEL_REGISTRY
-- Quản lý nhiều version model, phục vụ upload/rollback động.
-- ------------------------------------------------------------
create table if not exists public.model_registry (
  id bigint generated by default as identity primary key,
  model_key text not null,
  model_version text not null,
  model_url text not null,
  uploaded_at timestamptz not null default now()
);

alter table public.model_registry
  add column if not exists model_key text,
  add column if not exists model_version text,
  add column if not exists model_url text,
  add column if not exists uploaded_at timestamptz;

update public.model_registry
set uploaded_at = coalesce(uploaded_at, now());

alter table public.model_registry
  alter column uploaded_at set default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'model_registry_model_key_check'
      and conrelid = 'public.model_registry'::regclass
  ) then
    alter table public.model_registry
      add constraint model_registry_model_key_check
      check (model_key in ('cnn','resnet50','densenet121','efficientnetb0'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'model_registry_model_key_model_version_key'
      and conrelid = 'public.model_registry'::regclass
  ) then
    alter table public.model_registry
      add constraint model_registry_model_key_model_version_key
      unique (model_key, model_version);
  end if;
end $$;

-- ------------------------------------------------------------
-- 4. MONITOR_SESSIONS
-- ------------------------------------------------------------
create table if not exists public.monitor_sessions (
  id uuid primary key,
  user_id uuid references auth.users(id) on delete cascade,
  started_at timestamptz default now()
);

alter table public.monitor_sessions
  add column if not exists user_id uuid,
  add column if not exists model_key text,
  add column if not exists started_at timestamptz,
  add column if not exists ended_at timestamptz,
  add column if not exists created_at timestamptz;

update public.monitor_sessions
set
  model_key = coalesce(model_key, 'cnn'),
  started_at = coalesce(started_at, now()),
  created_at = coalesce(created_at, now());

alter table public.monitor_sessions
  alter column model_key set default 'cnn',
  alter column started_at set default now(),
  alter column created_at set default now();

create index if not exists monitor_sessions_user_started_idx
  on public.monitor_sessions(user_id, started_at desc);

-- ------------------------------------------------------------
-- 5. POSTURE_EVENTS
-- ------------------------------------------------------------
create table if not exists public.posture_events (
  id bigint generated by default as identity primary key
);

alter table public.posture_events
  add column if not exists user_id uuid,
  add column if not exists session_id uuid,
  add column if not exists posture text,
  add column if not exists confidence real,
  add column if not exists model_key text,
  add column if not exists started_at timestamptz,
  add column if not exists duration_seconds integer,
  add column if not exists created_at timestamptz;

update public.posture_events
set
  confidence = coalesce(confidence, 0),
  model_key = coalesce(model_key, 'cnn'),
  started_at = coalesce(started_at, now()),
  duration_seconds = coalesce(duration_seconds, 1),
  created_at = coalesce(created_at, now());

alter table public.posture_events
  alter column confidence set default 0,
  alter column model_key set default 'cnn',
  alter column started_at set default now(),
  alter column duration_seconds set default 1,
  alter column created_at set default now();

create index if not exists posture_events_user_started_idx
  on public.posture_events(user_id, started_at desc);

-- ------------------------------------------------------------
-- 6. ALERTS
-- V5 dùng alerts chủ yếu để ghi cảnh báo âm thanh.
-- ------------------------------------------------------------
create table if not exists public.alerts (
  id bigint generated by default as identity primary key
);

alter table public.alerts
  add column if not exists user_id uuid,
  add column if not exists session_id uuid,
  add column if not exists posture text,
  add column if not exists duration_seconds integer,
  add column if not exists channel text,
  add column if not exists model_key text,
  add column if not exists sent_at timestamptz;

update public.alerts
set
  duration_seconds = coalesce(duration_seconds, 0),
  channel = coalesce(channel, 'audio'),
  model_key = coalesce(model_key, 'cnn'),
  sent_at = coalesce(sent_at, now());

alter table public.alerts
  alter column duration_seconds set default 0,
  alter column channel set default 'audio',
  alter column model_key set default 'cnn',
  alter column sent_at set default now();

create index if not exists alerts_user_sent_idx
  on public.alerts(user_id, sent_at desc);

-- ------------------------------------------------------------
-- 7. REPORTS
-- Báo cáo tổng hợp gửi phụ huynh khi kết thúc phiên.
-- ------------------------------------------------------------
create table if not exists public.reports (
  id bigint generated by default as identity primary key
);

alter table public.reports
  add column if not exists user_id uuid,
  add column if not exists session_id uuid,
  add column if not exists recipient text,
  add column if not exists monitored_seconds integer,
  add column if not exists bad_seconds integer,
  add column if not exists correct_percent real,
  add column if not exists model_key text,
  add column if not exists sent_at timestamptz;

update public.reports
set
  recipient = coalesce(recipient, ''),
  monitored_seconds = coalesce(monitored_seconds, 0),
  bad_seconds = coalesce(bad_seconds, 0),
  correct_percent = coalesce(correct_percent, 0),
  model_key = coalesce(model_key, 'cnn'),
  sent_at = coalesce(sent_at, now());

alter table public.reports
  alter column recipient set default '',
  alter column monitored_seconds set default 0,
  alter column bad_seconds set default 0,
  alter column correct_percent set default 0,
  alter column model_key set default 'cnn',
  alter column sent_at set default now();

create index if not exists reports_user_sent_idx
  on public.reports(user_id, sent_at desc);

-- ------------------------------------------------------------
-- 8. STORAGE BUCKET
-- Public bucket để browser load TensorFlow.js model.json + *.bin
-- ------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('ai-models', 'ai-models', true)
on conflict (id) do update set public = true;

-- ------------------------------------------------------------
-- 9. RLS
-- Backend dùng service_role; browser không query trực tiếp nghiệp vụ.
-- ------------------------------------------------------------
alter table public.user_profiles enable row level security;
alter table public.system_config enable row level security;
alter table public.model_registry enable row level security;
alter table public.monitor_sessions enable row level security;
alter table public.posture_events enable row level security;
alter table public.alerts enable row level security;
alter table public.reports enable row level security;

-- ------------------------------------------------------------
-- 10. Ghi nhận migration
-- ------------------------------------------------------------
insert into public.app_migrations(version)
values ('v5-user-super-admin')
on conflict (version) do nothing;

commit;

-- ============================================================
-- KIỂM TRA SAU MIGRATE
-- Chạy riêng các câu dưới đây sau khi migration thành công.
-- ============================================================

-- select * from public.app_migrations order by applied_at desc;
-- select * from public.system_config;
-- select table_name
-- from information_schema.tables
-- where table_schema = 'public'
--   and table_name in (
--     'user_profiles','system_config','model_registry',
--     'monitor_sessions','posture_events','alerts','reports'
--   )
-- order by table_name;
--
-- select id, name, public
-- from storage.buckets
-- where id = 'ai-models';

-- ============================================================
-- DỌN CỘT CŨ (KHÔNG BẮT BUỘC)
-- Chỉ chạy sau khi hệ thống v5 hoạt động ổn định và đã backup.
-- ============================================================

-- alter table public.user_profiles drop column if exists selected_model;
-- alter table public.user_profiles drop column if exists parent_alert_seconds;
-- alter table public.user_profiles drop column if exists report_schedule;
