-- PostureGuard AI v3

create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  student_name text not null default '',
  parent_email text not null default '',
  local_alert_seconds integer not null default 10 check (local_alert_seconds >= 3),
  email_enabled boolean not null default true,
  report_schedule text not null default 'session_end' check (report_schedule in ('session_end','daily')),
  updated_at timestamptz not null default now()
);

create table if not exists public.system_config (
  id integer primary key check (id=1),
  selected_model text not null default 'cnn'
    check (selected_model in ('cnn','resnet50','densenet121','efficientnetb0')),
  model_version text not null default 'v1',
  model_url text not null default '',
  updated_at timestamptz not null default now()
);
insert into public.system_config(id,selected_model,model_version,model_url)
values(1,'cnn','v1','')
on conflict (id) do nothing;

create table if not exists public.monitor_sessions (
  id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  model_key text not null default 'cnn',
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists monitor_sessions_user_started_idx on public.monitor_sessions(user_id,started_at desc);

create table if not exists public.posture_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id uuid,
  posture text not null check (posture in ('upright','leaning_left','leaning_right','leaning_backward')),
  confidence real not null default 0,
  model_key text not null default 'cnn',
  started_at timestamptz not null default now(),
  duration_seconds integer not null default 1 check (duration_seconds > 0),
  created_at timestamptz not null default now()
);
create index if not exists posture_events_user_started_idx on public.posture_events(user_id,started_at desc);

create table if not exists public.alerts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id uuid,
  posture text not null,
  duration_seconds integer not null default 0,
  channel text not null default 'audio',
  model_key text not null default 'cnn',
  sent_at timestamptz not null default now()
);
create index if not exists alerts_user_sent_idx on public.alerts(user_id,sent_at desc);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id uuid,
  recipient text not null,
  monitored_seconds integer not null default 0,
  bad_seconds integer not null default 0,
  correct_percent real not null default 0,
  model_key text not null default 'cnn',
  sent_at timestamptz not null default now()
);

alter table public.user_profiles enable row level security;
alter table public.system_config enable row level security;
alter table public.monitor_sessions enable row level security;
alter table public.posture_events enable row level security;
alter table public.alerts enable row level security;
alter table public.reports enable row level security;


create table if not exists public.model_registry (
  id bigint generated by default as identity primary key,
  model_key text not null check (model_key in ('cnn','resnet50','densenet121','efficientnetb0')),
  model_version text not null,
  model_url text not null,
  uploaded_at timestamptz not null default now(),
  unique(model_key, model_version)
);

alter table public.model_registry enable row level security;

-- Storage bucket cho model AI
insert into storage.buckets (id, name, public)
values ('ai-models', 'ai-models', true)
on conflict (id) do update set public = true;
