const CFG=window.POSTUREGUARD_CONFIG||{};
const {createClient}=window.supabase;
const supabase=createClient(CFG.SUPABASE_URL,CFG.SUPABASE_ANON_KEY);
const CLASS_NAMES=['leaning_backward','leaning_left','leaning_right','upright'];
const CORRECT_CLASS='upright',MIN_CONFIDENCE=.65,SMOOTHING_FRAMES=8,PREDICT_INTERVAL_MS=600;
const MODEL_NAMES={cnn:'CNN',resnet50:'ResNet50',densenet121:'DenseNet121',efficientnetb0:'EfficientNet-B0'};
const DISPLAY={leaning_backward:'Ngả về sau',leaning_left:'Nghiêng trái',leaning_right:'Nghiêng phải',upright:'Tư thế đúng',unknown:'Chưa xác định'};
const $=id=>document.getElementById(id),sleep=ms=>new Promise(r=>setTimeout(r,ms));
let currentUser=null,profile=null,systemConfig=null,adminToken=sessionStorage.getItem('pg_admin_token')||null;
let model=null,activeModelCacheKey=null,stream=null,cameraRunning=false,predictLoopToken=0,history=[],badStartAt=null,localAlertSent=false,sessionId=null,currentEpisode=null,ratioChart=null,postureChart=null;
function msg(el,kind,text){el.className=`message ${kind}`;el.textContent=text}
async function userApi(path,options={}){const s=(await supabase.auth.getSession()).data.session;if(!s)throw new Error('Phiên đăng nhập đã hết hạn');const r=await fetch(`/.netlify/functions/${path}`,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.access_token}`,...(options.headers||{})}});const t=await r.text(),d=t?JSON.parse(t):{};if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
async function adminApi(path,options={}){if(!adminToken)throw new Error('Chưa đăng nhập Super Admin');const r=await fetch(`/.netlify/functions/${path}`,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${adminToken}`,...(options.headers||{})}});const t=await r.text(),d=t?JSON.parse(t):{};if(!r.ok){if(r.status===401){adminToken=null;sessionStorage.removeItem('pg_admin_token')}throw new Error(d.error||`HTTP ${r.status}`)}return d}
function showOnly(s){$('authScreen').hidden=s!=='auth';$('userApp').hidden=s!=='user';$('adminApp').hidden=s!=='admin'}
function showAuthMode(m){$('loginForm').hidden=m!=='login';$('registerForm').hidden=m!=='register';$('adminLoginForm').hidden=m!=='admin';$('showLogin').classList.toggle('active',m==='login');$('showRegister').classList.toggle('active',m==='register');$('showAdminLogin').classList.toggle('active',m==='admin')}
async function init(){if(adminToken){try{await loadAdminConsole();showOnly('admin');return}catch{adminToken=null;sessionStorage.removeItem('pg_admin_token')}}const {data:{session}}=await supabase.auth.getSession();if(session){await enterUserApp(session);return}showOnly('auth')}
async function login(){const {error}=await supabase.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});if(error)return msg($('authMessage'),'error',error.message);const {data:{session}}=await supabase.auth.getSession();await enterUserApp(session)}
async function register(){const p1=$('registerPassword').value,p2=$('registerPassword2').value;if(p1!==p2)return msg($('authMessage'),'error','Mật khẩu xác nhận không khớp');const {data,error}=await supabase.auth.signUp({email:$('registerEmail').value.trim(),password:p1});if(error)return msg($('authMessage'),'error',error.message);if(data.session){await userApi('profile',{method:'POST',body:JSON.stringify({student_name:$('registerStudentName').value.trim(),parent_email:$('registerParentEmail').value.trim(),local_alert_seconds:10,email_enabled:true})});await enterUserApp(data.session)}else{msg($('authMessage'),'ok','Đăng ký thành công. Hãy xác nhận email rồi đăng nhập.');showAuthMode('login')}}
async function adminLogin(){const r=await fetch('/.netlify/functions/admin-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('adminUsername').value.trim(),password:$('adminPassword').value})});const t=await r.text(),d=t?JSON.parse(t):{};if(!r.ok)return msg($('authMessage'),'error',d.error||'Đăng nhập admin thất bại');adminToken=d.token;sessionStorage.setItem('pg_admin_token',adminToken);await supabase.auth.signOut();await loadAdminConsole();showOnly('admin')}
async function logoutUser(){if(cameraRunning)await stopCamera();await supabase.auth.signOut();currentUser=null;showOnly('auth');showAuthMode('login')}
function logoutAdmin(){adminToken=null;sessionStorage.removeItem('pg_admin_token');showOnly('auth');showAuthMode('login')}
async function enterUserApp(session){currentUser=session.user;$('userBadge').textContent=currentUser.email;await Promise.all([loadProfile(),loadPublicConfig()]);await loadSelectedModel(true);showOnly('user')}
async function loadProfile(){profile=await userApi('profile',{method:'GET'});$('studentName').value=profile.student_name||'';$('parentEmail').value=profile.parent_email||'';$('localAlertSeconds').value=profile.local_alert_seconds||10;$('emailEnabled').checked=profile.email_enabled!==false}
async function saveSettings(){const next={student_name:$('studentName').value.trim(),parent_email:$('parentEmail').value.trim(),local_alert_seconds:Number($('localAlertSeconds').value||10),email_enabled:$('emailEnabled').checked};try{await userApi('profile',{method:'POST',body:JSON.stringify(next)});profile=next;msg($('settingsMessage'),'ok','Đã lưu cài đặt cá nhân.')}catch(e){msg($('settingsMessage'),'error',e.message)}}
async function loadPublicConfig(){systemConfig=await userApi('public-config',{method:'GET'})}
async function loadSelectedModel(force=false){const key=systemConfig?.selected_model||'cnn',version=systemConfig?.model_version||'v1',url=systemConfig?.model_url;if(!url){$('modelBadge').textContent='Chưa có model active';$('modelBadge').className='badge badge-bad';return}const cacheKey=`${key}:${version}:${url}`;if(!force&&model&&activeModelCacheKey===cacheKey)return;$('modelBadge').textContent=`Đang tải ${MODEL_NAMES[key]} ${version}…`;$('modelBadge').className='badge badge-warn';if(model&&model.dispose)model.dispose();model=null;try{const sep=url.includes('?')?'&':'?';model=await tf.loadGraphModel(`${url}${sep}v=${encodeURIComponent(version)}&t=${encodeURIComponent(systemConfig.updated_at||Date.now())}`);activeModelCacheKey=cacheKey;$('modelBadge').textContent=`${MODEL_NAMES[key]} ${version}`;$('modelBadge').className='badge badge-ok';$('activeModelName').textContent=`${MODEL_NAMES[key]} ${version}`}catch(e){console.error(e);$('modelBadge').textContent='Lỗi tải model';$('modelBadge').className='badge badge-bad'}}
function preprocess(source){return tf.tidy(()=>tf.browser.fromPixels(source,3).resizeBilinear([224,224]).toFloat().expandDims(0))}
async function infer(source){if(!model)throw new Error('Model chưa sẵn sàng');const input=preprocess(source);let out;try{out=await model.executeAsync(input);const tensor=Array.isArray(out)?out[0]:out,probs=Array.from(await tensor.data());if(Array.isArray(out))out.forEach(t=>t.dispose());else out.dispose();const idx=probs.indexOf(Math.max(...probs)),confidence=probs[idx]||0,raw=CLASS_NAMES[idx]||'unknown';return{label:confidence>=MIN_CONFIDENCE?raw:'unknown',confidence,probs}}finally{input.dispose()}}
function stableLabel(label){history.push(label);if(history.length>SMOOTHING_FRAMES)history.shift();const valid=history.filter(x=>x!=='unknown');if(!valid.length)return'unknown';const c={};valid.forEach(x=>c[x]=(c[x]||0)+1);return Object.entries(c).sort((a,b)=>b[1]-a[1])[0][0]}
async function startCamera(){if(!model)return alert('Model chưa sẵn sàng');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:960},height:{ideal:720}},audio:false});$('video').srcObject=stream;cameraRunning=true;history=[];badStartAt=null;localAlertSent=false;currentEpisode=null;sessionId=crypto.randomUUID();await userApi('session',{method:'POST',body:JSON.stringify({action:'start',session_id:sessionId,model_key:systemConfig.selected_model})});$('startCamera').disabled=true;$('stopCamera').disabled=false;$('emailReportState').textContent='Chưa gửi';const token=++predictLoopToken;predictLoop(token)}
async function stopCamera(){cameraRunning=false;++predictLoopToken;if(currentEpisode)await closeEpisode(Date.now());if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;$('video').srcObject=null;$('startCamera').disabled=false;$('stopCamera').disabled=true;if(sessionId){await userApi('session',{method:'POST',body:JSON.stringify({action:'stop',session_id:sessionId})});if(profile?.email_enabled){try{$('emailReportState').textContent='Đang gửi…';await userApi('send-report',{method:'POST',body:JSON.stringify({session_id:sessionId})});$('emailReportState').textContent='Đã gửi'}catch(e){console.error(e);$('emailReportState').textContent='Lỗi gửi'}}}sessionId=null;setState('idle','Đã tắt camera')}
async function predictLoop(token){while(cameraRunning&&token===predictLoopToken){if($('video').readyState>=2){try{const r=await infer($('video'));await handlePosture(stableLabel(r.label),r.confidence)}catch(e){console.error(e)}}await sleep(PREDICT_INTERVAL_MS)}}
async function handlePosture(label,confidence){const now=Date.now();$('confidence').textContent=`${(confidence*100).toFixed(1)}%`;if(!currentEpisode||currentEpisode.label!==label){if(currentEpisode)await closeEpisode(now);currentEpisode={label,startedAt:now,maxConfidence:confidence}}else currentEpisode.maxConfidence=Math.max(currentEpisode.maxConfidence,confidence);if(label===CORRECT_CLASS){badStartAt=null;localAlertSent=false;$('badDuration').textContent='0.0s';$('localAlertState').textContent='Chưa';setState('good','✅ Tư thế đúng');msg($('cameraMessage'),'ok','Bạn đang ngồi đúng tư thế.');return}if(label==='unknown'){badStartAt=null;$('badDuration').textContent='0.0s';setState('unknown','⚠️ Chưa xác định');return}if(!badStartAt){badStartAt=now;localAlertSent=false}const seconds=(now-badStartAt)/1000;$('badDuration').textContent=`${seconds.toFixed(1)}s`;setState('bad',`❌ ${DISPLAY[label]}`);msg($('cameraMessage'),'error',`Phát hiện ${DISPLAY[label].toLowerCase()} trong ${seconds.toFixed(0)} giây.`);if(!localAlertSent&&seconds>=Number(profile.local_alert_seconds||10)){localAlertSent=true;$('localAlertState').textContent='Đã cảnh báo';speak(`Bạn đang ${DISPLAY[label].toLowerCase()}. Hãy điều chỉnh lại tư thế ngồi.`);await userApi('alert-log',{method:'POST',body:JSON.stringify({session_id:sessionId,posture:label,duration_seconds:Math.round(seconds),model_key:systemConfig.selected_model,channel:'audio'})})}}
async function closeEpisode(endedAt){const ep=currentEpisode;currentEpisode=null;if(!ep||!sessionId||ep.label==='unknown')return;await userApi('event',{method:'POST',body:JSON.stringify({session_id:sessionId,posture:ep.label,confidence:ep.maxConfidence,started_at:new Date(ep.startedAt).toISOString(),duration_seconds:Math.max(1,Math.round((endedAt-ep.startedAt)/1000)),model_key:systemConfig.selected_model})})}
function speak(text){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='vi-VN';speechSynthesis.speak(u)}
function setState(kind,text){$('postureState').textContent=text;$('postureState').className=`state state-${kind}`}
async function loadDashboard(){try{const data=await userApi('dashboard?days=7',{method:'GET'}),monitored=Number(data.monitored_seconds||0),bad=Number(data.bad_seconds||0),correct=monitored>0?Math.max(0,(monitored-bad)/monitored*100):0;$('kpiMonitor').textContent=`${Math.round(monitored/60)} phút`;$('kpiBad').textContent=`${Math.round(bad/60)} phút`;$('kpiCorrect').textContent=monitored?`${correct.toFixed(1)}%`:'--';$('kpiAlerts').textContent=data.alerts?.length||0;renderCharts(monitored,bad,data.bad_by_posture||{});renderAlerts(data.alerts||[])}catch(e){console.error(e)}}
function renderCharts(monitored,bad,byPosture){if(ratioChart)ratioChart.destroy();if(postureChart)postureChart.destroy();ratioChart=new Chart($('ratioChart'),{type:'doughnut',data:{labels:['Ngồi đúng','Ngồi sai'],datasets:[{data:[Math.max(0,monitored-bad),bad],backgroundColor:['#36d399','#ff6b6b']}]},options:{plugins:{legend:{labels:{color:'#dbe5ff'}}}}});const keys=['leaning_left','leaning_right','leaning_backward'];postureChart=new Chart($('postureChart'),{type:'bar',data:{labels:keys.map(k=>DISPLAY[k]),datasets:[{label:'Phút',data:keys.map(k=>(byPosture[k]||0)/60),backgroundColor:'#6ea8fe'}]},options:{scales:{x:{ticks:{color:'#dbe5ff'}},y:{ticks:{color:'#dbe5ff'}}},plugins:{legend:{labels:{color:'#dbe5ff'}}}}})}
function renderAlerts(rows){$('alertRows').innerHTML=rows.length?rows.map(a=>`<tr><td>${new Date(a.sent_at).toLocaleString('vi-VN')}</td><td>${DISPLAY[a.posture]||a.posture}</td><td>${a.duration_seconds}s</td><td>${MODEL_NAMES[a.model_key]||a.model_key||''}</td><td>${a.channel}</td></tr>`).join(''):'<tr><td colspan="5">Chưa có cảnh báo</td></tr>'}
async function loadAdminConsole(){await Promise.all([loadAdminConfig(),loadModelRegistry(),loadEmailStatus()])}
async function loadAdminConfig(){const c=await adminApi('system-config',{method:'GET'});$('globalModel').value=c.selected_model||'cnn';$('globalModelVersion').value=c.model_version||'v1';$('globalModelDisplay').textContent=`${MODEL_NAMES[c.selected_model]||c.selected_model} ${c.model_version||''}`;$('globalModelUrl').textContent=c.model_url||'--'}
async function saveAdminConfig(){try{await adminApi('system-config',{method:'POST',body:JSON.stringify({selected_model:$('globalModel').value,model_version:$('globalModelVersion').value.trim()||'v1'})});msg($('systemMessage'),'ok','Đã activate model/version.');await loadAdminConfig()}catch(e){msg($('systemMessage'),'error',e.message)}}
async function uploadModel(){const key=$('uploadModelKey').value,version=$('uploadModelVersion').value.trim(),jsonFile=$('modelJsonFile').files[0],bins=Array.from($('modelBinFiles').files||[]),activate=$('activateAfterUpload').checked;if(!version)return msg($('uploadModelMessage'),'error','Thiếu version');if(!jsonFile)return msg($('uploadModelMessage'),'error','Thiếu model.json');if(!bins.length)return msg($('uploadModelMessage'),'error','Thiếu file *.bin');const form=new FormData();form.append('model_key',key);form.append('model_version',version);form.append('activate',activate?'true':'false');form.append('model_json',jsonFile);bins.forEach(f=>form.append('weight_files',f));try{msg($('uploadModelMessage'),'info','Đang upload…');const r=await fetch('/.netlify/functions/upload-model',{method:'POST',headers:{Authorization:`Bearer ${adminToken}`},body:form}),t=await r.text(),d=t?JSON.parse(t):{};if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);msg($('uploadModelMessage'),'ok','Upload thành công.');await loadModelRegistry();if(activate)await loadAdminConfig()}catch(e){msg($('uploadModelMessage'),'error',e.message)}}
async function loadModelRegistry(){const d=await adminApi('model-registry',{method:'GET'}),rows=d.items||[];$('modelRegistryRows').innerHTML=rows.length?rows.map(x=>`<tr><td>${MODEL_NAMES[x.model_key]||x.model_key}</td><td>${x.model_version}</td><td>${new Date(x.uploaded_at).toLocaleString('vi-VN')}</td><td class="mono-cell">${x.model_url}</td></tr>`).join(''):'<tr><td colspan="4">Chưa có model</td></tr>'}
async function loadEmailStatus(){const s=await adminApi('admin-email-status',{method:'GET'});$('systemEmailSender').textContent=s.sender||'Chưa cấu hình';$('systemEmailStatus').textContent=s.configured?'Đã cấu hình':'Chưa cấu hình'}
async function adminTestEmail(){try{msg($('adminEmailMessage'),'info','Đang gửi…');await adminApi('admin-email-status',{method:'POST',body:JSON.stringify({to:$('adminTestRecipient').value.trim()})});msg($('adminEmailMessage'),'ok','Đã gửi email test.')}catch(e){msg($('adminEmailMessage'),'error',e.message)}}
document.querySelectorAll('[data-user-tab]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-user-tab]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('#userApp .panel').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$(`user-tab-${btn.dataset.userTab}`).classList.add('active');if(btn.dataset.userTab==='dashboard')loadDashboard()}));
document.querySelectorAll('[data-admin-tab]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-admin-tab]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('#adminApp .panel').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$(`admin-tab-${btn.dataset.adminTab}`).classList.add('active')}));
$('showLogin').onclick=()=>showAuthMode('login');$('showRegister').onclick=()=>showAuthMode('register');$('showAdminLogin').onclick=()=>showAuthMode('admin');$('loginBtn').onclick=login;$('registerBtn').onclick=register;$('adminLoginBtn').onclick=adminLogin;$('logoutBtn').onclick=logoutUser;$('adminLogoutBtn').onclick=logoutAdmin;$('startCamera').onclick=startCamera;$('stopCamera').onclick=stopCamera;$('saveSettings').onclick=saveSettings;$('refreshDashboard').onclick=loadDashboard;$('saveSystemConfig').onclick=saveAdminConfig;$('uploadModelBtn').onclick=uploadModel;$('adminTestEmailBtn').onclick=adminTestEmail;
init();
